### ISSUE TITLE
python3 btgenbot.py_Error

### ISSUE THREAD

**Issue by lhc-code** [AIRLab-POLIMI/BTGenBot#3] opened 2024-04-01 06:53 UTC
**Thanks to your help last time**, I was able to successfully complete the demo. I really appreciate it. The demo results showed that the fine-tuned version and the base model produced identical outputs. I am running btgenbot.py because I want to understand the difference between the two.

I am experiencing the following error.

(btgenbotv1) kime@DESKTOP-NFV50BR:~/BTGenBot-2/bt_generator$ python3 btgenbot.py
Traceback (most recent call last):
  File "/home/kime/BTGenBot-2/bt_generator/btgenbot.py", line 84, in submit
    self.generate(example_task, example_output, task)
  File "/home/kime/BTGenBot-2/bt_generator/btgenbot.py", line 92, in generate
    with open(config_file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'bt_generator/config/params.yaml'
Aborted

I am attaching the settings of the para.yaml file. I am uncertain if I have entered the correct address for the settings. Do you think there is something wrong with the local or remote address?
![20240401_154823](https://github.com/AIRLab-POLIMI/BTGenBot/assets/121343852/6d69bdd2-e2b7-4337-bce6-209e2576795f)
![20240401_155412](https://github.com/AIRLab-POLIMI/BTGenBot/assets/121343852/124ab71e-58d4-4b2d-9c1d-a9978e04b1e9)

Thank you once again.

**Comment by RiccardoIzzo** [comment] 2024-04-04 10:54
Path issue fixed in the last commit, a path in btgenbot.py occasionally failed in certain environments. 
The parameters in params.yaml are confirmed to be correct: however double-check your specified directories.

**Comment by RiccardoIzzo** [comment] 2024-04-08 10:38
Regarding the output issue, the fine-tuned version and the base model produced identical outputs due to an error in the inference notebook. Now it has been fixed.

**Closed as completed by RiccardoIzzo** 2024-04-08 10:38 UTC
